Remove casts introduced in previous schema change
RedHatInsights/notifications-backend pull request #1457
Opened 2022-09-01 18:16 UTC by josejulio

2022-09-06 22:03 UTC, josejulio commented
@gwenneg This is only waiting the release of the schema (already started the release process)

2022-09-07 07:08 UTC, gwenneg requested changes

2022-09-07 07:08 UTC, gwenneg commented on engine/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java
> +>>>>>>> 4d1fa9df (Remove casts introduced in previous schema change)
```suggestion
```

2022-09-07 07:26 UTC, gwenneg approved these changes
LGTM

2022-09-07 07:26 UTC, merged