[RHCLOUD-23955] update Patch email templates according UXD guidelines
RedHatInsights/notifications-backend pull request #1719
Opened 2023-01-26 13:26 UTC by g-duval

![image](https://user-images.githubusercontent.com/117720964/214846805-267e02e2-1377-4a0a-9430-8e490e64d3c9.png)

![image](https://user-images.githubusercontent.com/117720964/214846825-7cf3ef1c-cb11-41d9-b49b-d8e0860f66e0.png)

2023-01-26 19:15 UTC, josejulio requested changes

2023-01-26 20:12 UTC, g-duval commented on common/src/main/java/com/redhat/cloud/notifications/config/FeatureFlipper.java
> +    @ConfigProperty(name = "notifications.use-parch-email-templates-v2.enabled", defaultValue = "false")
Oups... thanks

2023-01-26 20:13 UTC, g-duval commented on common/src/main/java/com/redhat/cloud/notifications/config/FeatureFlipper.java
> +        this.patchEmailTemplatesV2Enabled = patchEmailTemplatesV2Enabled;
Ok

2023-01-26 20:15 UTC, g-duval commented on engine/src/main/resources/templates/Common/insightsEmailBody.html
> +            font-weight: bold;
It have to impact all templates, I didn't noticed that when I added this common file bases on Policies, but according UXD mockups, table headers have to be Bold, but not full uppercase.

2023-01-30 13:40 UTC, josejulio approved these changes
lgtm

2023-02-01 11:19 UTC, merged