[RHCLOUD-22813] Handle provided context.host_url in integration templates
RedHatInsights/notifications-backend pull request #3221
Opened 2024-12-19 17:37 UTC by jessicarod7

## Jira issue

https://issues.redhat.com/browse/RHCLOUD-22813

## Description

Currently, URLs in PagerDuty and Camel notifications are constructed by the PagerDutyTransformer, or one of three [Qute](https://quarkus.io/guides/qute) templates, respectively. Each one has a slightly different way of handling URLs, and the Camel templates are not the ones currently shown in this repo.

This PR creates a new class, `InsightsUrlsBuilder`, which provides consistent construction of the two URLs for all integrations:

- `data.inventory_url` represents a link to the specific host, cluster, or inventory item in the Console that generated the message. If `data.context.host_url` is provided, it will be used here.
- `data.application_url` links back to the application that generated the event.

The PR will also make it easy to modify the URL format in a followup issue.

## Database migration

A new migration file (`V1.109.0`) has been added. It takes the current templates used in the Notifications database, and updates them to use the new URLs.

> [!NOTE]
> 
> **One change has been made to the existing format:** Camel messages no longer contain a leading `\n`. This caused unexpected failures while testing the Slack processor, and weirdly did not fail with the Teams processor when it should have.

## Testing

- Updated connector-pagerduty tests to emulate the new URL builder on the engine side.
- Updated `CamelProcessorTest` implementers to use the new URLs in their Qute templates
- Added a new test for PagerDuty and Camel to verify that `data.context.host_url` will always be used if present

## Example

Using the following trimmed output from `BaseTransformer`:

```json5
{
  "bundle": "rhel",
  "application": "advisor",
  "event_type": "new-recommendation",
  "timestamp": "2024-12-19T15:21:45.129372",
  // trimmed
  "context": {
    "inventory_id": "6eaaa39c-55f7-4f45-81a9-84c75b1475d6",
    "hostname": "my-computer-jrodri",
    "display_name": "my-computer-jrodri",
    "host_url": "https://console.redhat.com/insights/inventory/some-unique-host-url-path",
    "tags": []
  },
  "events": [
    {
      // one event, trimmed
    },
    {
      // another event, trimmed
    }
  ],
  "source": {
    "application": {"display_name": "Advisor"},
    "bundle": {"display_name": "Red Hat Enterprise Linux"}
  }
  "environment_url": "https://console.redhat.com"
}
```

And the new Microsoft Teams template:

```
{"text":"{#if data.context.display_name??}[{data.context.display_name}]({data.inventory_url}) triggered {data.events.size()} event{#if data.events.size() \u003e 1}s{/if}{#else}{data.events.size()} event{#if data.events.size() \u003e 1}s{/if} triggered{/if} from {data.source.application.display_name} - {data.source.bundle.display_name}. [Open {data.source.application.display_name}]({data.application_url})"}
```

We generate this message:

```markdown
[my-computer-jrodri](https://console.redhat.com/insights/inventory/some-unique-host-url-path) triggered 2 events from Advisor - Red Hat Enterprise Linux. [Open Advisor](https://console.redhat.com/insights/advisor)
```

2025-01-07 13:44 UTC, g-duval requested changes
Awesome work Jessica :)
Because tis PR will involve some braking changes, I think it should be split in two PRs for camel processor case, like:
1) Introduce new entries into data source object
2) Update Qute templates and remove deprecated data from data source object (like environnment_url)

WDYT?

2025-01-07 13:44 UTC, g-duval commented on connector-pagerduty/src/main/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyTransformer.java
> +    public static final String LINKS = "links";
If I understood properly, `LINKS` property will include only one link right? then shouldn't we remove the `s`?

2025-01-07 13:44 UTC, g-duval commented on engine/src/main/java/com/redhat/cloud/notifications/processors/camel/CamelProcessor.java
> -        data.put("environment_url", environment.url());
> [!WARNING]
> It involves a breaking change

2025-01-07 13:44 UTC, g-duval commented on engine/src/main/java/com/redhat/cloud/notifications/processors/InsightsUrlsBuilder.java
> +        }
I don't have the same understanding of current Qute templates conditions as you have, could you please double check?

2025-01-07 13:44 UTC, g-duval commented on engine/src/main/java/com/redhat/cloud/notifications/processors/InsightsUrlsBuilder.java
> +        }
I don't have the same understanding of current Qute templates conditions as you have, could you please double check?

2025-01-07 16:12 UTC, jessicarod7 commented on database/src/main/resources/db/migration/V1.109.0__RHCLOUD-22813_update_template_host_app_urls.sql
> +SET data = '{"text":"{#if data.context.display_name??}[{data.context.display_name}]({data.inventory_url}) triggered {data.events.size()} event{#if data.events.size() \u003e 1}s{/if}{#else}{data.event
This one was a bit confusing, when I queried the current configuration with Gabi, the templates used `\u00e3`, but I'm not sure if that was just a side effect of how they were modified. I'll switch it back since the existing templates use `>`.

2025-01-07 16:41 UTC, jessicarod7 commented on engine/src/main/java/com/redhat/cloud/notifications/processors/InsightsUrlsBuilder.java
> +        }
Deciphering these was my favourite part 🙃

Here's the (formatted) template currently used by Teams, which was the most complete version I found. I've stripped out the Teams-specific JSON wrapper.

```
{#if data.context.display_name??}
    [{data.context.display_name}]({data.environment_url}
    {#if data.bundle == \"openshift\" and data.application == \"advisor\"}
        /openshift/insights/advisor/clusters/{data.context.display_name}
    {#else}
        /insights/inventory/
        {#if data.context.inventory_id??}
            {data.context.inventory_id}
        {#else}
            ?hostname_or_id={data.context.display_name}
        {/if}
    {/if}
    ) triggered {data.events.size()} event
    {#if data.events.size() \u003e 1}
        s
    {/if}
{#else}
    {data.events.size()} event
    {#if data.events.size() \u003e 1}
        s
    {/if} triggered
{/if}
 from {data.source.application.display_name} - {data.source.bundle.display_name}. [Open {data.source.application.display_name}]({data.environment_url}/
{#if data.bundle == \"openshift\"}
    openshift/
{/if}
{#if data.application == \"integrations\"}
    settings/
{#else}
    insights/
{/if}
{data.application})
```

The current logic for the inventory URL (the first one), after removing the Markdown:

```
{#if data.context.display_name??}
    {data.environment_url}
    {#if data.bundle == \"openshift\" and data.application == \"advisor\"}
        /openshift/insights/advisor/clusters/{data.context.display_name}
    {#else}
        /insights/inventory/
        {#if data.context.inventory_id??}
            {data.context.inventory_id}
        {#else}
            ?hostname_or_id={data.context.display_name}
        {/if}
    {/if}
{/if}
```

`variable??` is a Qute ["safe expression"](https://quarkus.io/guides/qute-reference#strict_rendering) that resolves to `null` if the value does not exist. Technically the new code is different, in that it will not accept an empty string, while the existing template would. Otherwise, the functionality is the same.

2025-01-07 16:52 UTC, jessicarod7 commented on engine/src/main/java/com/redhat/cloud/notifications/processors/InsightsUrlsBuilder.java
> +        }
Ah, found my confusion. The older Teams template in the repo ([V1.73.0 migration](https://github.com/RedHatInsights/notifications-backend/blob/20b0b1817c59a5a004ea17a8a1230943829b8fd6/database/src/main/resources/db/migration/V1.73.0__RHCLOUD-24813_teams_template.sql)) split this check in a weird way because it was also removing JSON, and I missed that in my implementation.

2025-01-09 09:28 UTC, g-duval commented on connector-pagerduty/src/test/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyTestUtils.java
> +class InsightsUrlsBuilder {
why dupplicating this class instead of using `engine/src/main/java/com/redhat/cloud/notifications/processors/InsightsUrlsBuilder.java` ?
if it is just to force the env url, you can use mokito like `Mockito.when(environment.url()).thenReturn(DEFAULT_ENVIRONMENT_URL);` on relevant tests.

2025-01-09 19:52 UTC, jessicarod7 commented on connector-pagerduty/src/main/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyTransformer.java
> +        clientLinks.put(CLIENT_URL, cloudEventPayload.getString(APPLICATION_URL));
It's used in the Teams messages as "Open Advisor", the logic is the same as [this suggested change](https://github.com/RedHatInsights/notifications-backend/pull/3221#discussion_r1905133881) and gets added to the cloud event [here](https://github.com/RedHatInsights/notifications-backend/blob/7c24129395315c53b457287f17bda22f88f00bca/engine/src/main/java/com/redhat/cloud/notifications/processors/pagerduty/PagerDutyProcessor.java#L82).

2025-01-09 20:02 UTC, jessicarod7 commented on connector-pagerduty/src/test/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyTestUtils.java
> +class InsightsUrlsBuilder {
The environment URL isn't the issue, [this duplicate actually hardcodes it](https://github.com/RedHatInsights/notifications-backend/blob/7c24129395315c53b457287f17bda22f88f00bca/connector-pagerduty/src/test/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyTestUtils.java#L240).

The PagerDuty connector currently does not have a test dependency on `notifications-engine`, so I can't import InsightsUrlsBuilder and have to duplicate the class instead. If it's not a big deal, I can just add the dependency and use that suggestion.

2025-01-09 20:05 UTC, jessicarod7 commented on connector-pagerduty/src/main/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyTransformer.java
> +        clientLinks.put(CLIENT_URL, cloudEventPayload.getString(APPLICATION_URL));
`APPLICATION_URL` is added to the cloud event [here](https://github.com/RedHatInsights/notifications-backend/blob/7c24129395315c53b457287f17bda22f88f00bca/engine/src/main/java/com/redhat/cloud/notifications/processors/pagerduty/PagerDutyProcessor.java#L82), before sending it to the PagerDuty connector. I do this since `notifications-engine` isn't a dependency, so I can't call InsightsUrlsBuilder directly.

2025-01-10 14:41 UTC, g-duval commented on connector-pagerduty/src/main/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyTransformer.java
> +        clientLinks.put(CLIENT_URL, cloudEventPayload.getString(APPLICATION_URL));
Ok thank you for those details

2025-01-10 14:41 UTC, g-duval commented on connector-pagerduty/src/main/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyTransformer.java
> +        message.mergeIn(getClientLinks(cloudEventPayload));
Ok

2025-01-10 14:50 UTC, g-duval commented on connector-pagerduty/src/test/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyTestUtils.java
> +class InsightsUrlsBuilder {
Ok sorry I didn't noticced it was in two distinct modules.
Then if engine is in charge to compute application and inventory url, why should we compute them again in pagerDuty connector, those url should be some simple input payload text properties like other fieds? WDYT?

2025-01-10 16:30 UTC, jessicarod7 commented on connector-pagerduty/src/test/java/com/redhat/cloud/notifications/connector/pagerduty/PagerDutyTestUtils.java
> +class InsightsUrlsBuilder {
Sure, I'll hardcode the fields. This was more useful when I was validating the logic for the connector.

2025-01-13 10:09 UTC, g-duval commented
/retest

2025-01-13 13:39 UTC, g-duval commented
@jessicarod7 it looks like those changes breaks [test_integration_pagerduty_event_triggered](https://ci.ext.devshift.net/job/RedHatInsights-notifications-backend-pr-check/7893/testReport/junit/tests.rest.integrations.test_pagerduty/TestPagerDutyIntegration/test_integration_pagerduty_event_triggered/) IQE test.
Could you please have a look and confirm if it was expected while waiting for a test case update?

2025-01-13 15:22 UTC, jessicarod7 commented
wasn't expecting this one to fail, looking into it

2025-01-14 11:34 UTC, MikelAlejoBR commented on engine/src/main/java/com/redhat/cloud/notifications/processors/InsightsUrlsBuilder.java
> +                if (!inventoryId.isEmpty()) {
I would suggest using `.isBlank()` instead of `isEmpty()`, in case we get sent a `"     "` string by mistake.

2025-01-17 19:01 UTC, jessicarod7 commented
@g-duval since I can no longer view the Jenkins build (and my attempts to deploy to ephemeral keep timing out), I'm unable to identify why that IQE test is failing

2025-01-20 08:53 UTC, MikelAlejoBR commented
/retest

2025-01-20 10:07 UTC, g-duval commented
@jessicarod7 , that's right, iqe test execution and logs were moved into Konflux last week, you can check them [here](https://console.redhat.com/application-pipeline/workspaces/hcc-integrations/applications/notifications/pipelineruns/notifications-iqe-integration-test-p4fp2/logs?task=run-iqe-cji).

2025-01-22 16:18 UTC, MikelAlejoBR approved these changes

2025-01-23 23:19 UTC, jessicarod7 commented
IQE issue fixed, I misformatted the `.links` section, which violated PD-CEF and caused PagerDuty to drop the alerts.

2025-01-24 08:42 UTC, g-duval commented
Awesome, thank you

2025-01-24 08:43 UTC, g-duval approved these changes
LGTM

2025-01-24 08:43 UTC, merged