NOTIF-190 Separate old and new cronjob
RedHatInsights/notifications-backend pull request #482
Opened 2021-08-12 12:13 UTC by bennetelli

2021-08-12 12:15 UTC, bennetelli commented
I separated the old cron job from the new Kafka input way.

The class was too huge IMO and with this separation it's easier to understand and easier to remove the old way later.

2021-08-16 16:41 UTC, josejulio commented on backend/src/main/java/com/redhat/cloud/notifications/processors/email/OldDailyEmailCronJob.java
> +    public Multi<NotificationHistory> process(Action action, List<Endpoint> endpoints) {
This methods processes `instant` emails also, it should remain in `EmailSubscriptionTypeProcessor`.

2021-08-16 16:41 UTC, josejulio commented on backend/src/main/java/com/redhat/cloud/notifications/processors/email/OldDailyEmailCronJob.java
> +    private Multi<NotificationHistory> sendInstantEmail(Action action, Set<Endpoint> endpoints, EmailTemplate emailTemplate) {
`instant email related`

2021-08-16 16:43 UTC, josejulio commented on backend/src/main/java/com/redhat/cloud/notifications/processors/email/EmailSubscriptionTypeProcessor.java
> -public class EmailSubscriptionTypeProcessor implements EndpointTypeProcessor {
We still need to implement `EndpintTypeProcessor`

2021-08-16 16:44 UTC, josejulio requested changes
I like the idea to group the soon-to-remove code, but these changes are also moving the mechanism to process instant emails.

2021-08-19 12:23 UTC, bennetelli commented
Will leave it as it is right now.

2021-08-19 12:23 UTC, closed without merging