feat(compliance): RHICOMPL-2566 introduce compliance templates
RedHatInsights/notifications-backend pull request #895
Opened 2022-01-10 14:38 UTC by skateman

2022-01-10 16:59 UTC, josejulio requested changes
Could you add the following changes?
A typo and some checkstyle fixes.

Also note that the Aggregator needs to be added to the [AggregatorFactory](https://github.com/RedHatInsights/notifications-backend/blob/0a7726abb3ec1085c068a5c8b53882d00d297987/backend/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/EmailPayloadAggregatorFactory.java#L31-L30) but not really needed right now

2022-01-10 16:59 UTC, josejulio commented on backend/src/main/java/com/redhat/cloud/notifications/processors/email/aggregators/ComplianceEmailAggregator.java
> +    public AnsibleEmailAggregator() {
```suggestion
    public ComplianceEmailAggregator() {
```

2022-01-10 16:59 UTC, josejulio commented on backend/src/main/resources/templates/Compliance/reportUploadFailedEmailTitle.txt
> +Red Hat Enterprise Linux - Compliance Instant Notification - {action.timestamp.toUtcFormat()} - Failed to uplad report of Policy '{action.content.policy}' from Host '{action.content.host}'
typo 

```suggestion
Red Hat Enterprise Linux - Compliance Instant Notification - {action.timestamp.toUtcFormat()} - Failed to upload report of Policy '{action.content.policy}' from Host '{action.content.host}'
```

2022-01-10 16:59 UTC, josejulio commented on backend/src/main/java/com/redhat/cloud/notifications/templates/Compliance.java
> +        public static native TemplateInstance reportUploadFailedEmailTitle();
```suggestion

        public static native TemplateInstance reportUploadFailedEmailTitle();
```

2022-01-10 16:59 UTC, josejulio commented on backend/src/main/java/com/redhat/cloud/notifications/templates/Compliance.java
> +        public static native TemplateInstance reportUploadFailedEmailBody();
```suggestion

        public static native TemplateInstance reportUploadFailedEmailBody();
```

2022-01-11 13:40 UTC, skateman commented
@josejulio adjusted what you requested and finalized the HTML templates. Can you please take a look?

2022-01-11 13:44 UTC, josejulio approved these changes
lgtm

2022-01-11 13:46 UTC, merged